services:
    db:
        image: postgres:alpine
        container_name: keycloak-postgres
        shm_size: 128mb
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - KEYCLOAK_POSTGRES_DB=${KEYCLOAK_POSTGRES_DB}
            - KEYCLOAK_POSTGRES_USER=${KEYCLOAK_POSTGRES_USER}
            - KEYCLOAK_POSTGRES_PASSWORD=${KEYCLOAK_POSTGRES_PASSWORD}
        volumes:
            - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql
            - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        ports:
            - "${POSTGRES_PORT}:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U keycloak"]
            interval: 10s
            timeout: 5s
            retries: 5

    keycloak:
        image: quay.io/keycloak/keycloak:26.4.0
        container_name: keycloak
        environment:
            - KC_DB=postgres
            - KC_DB_URL=jdbc:postgresql://db:${POSTGRES_PORT}/${KEYCLOAK_POSTGRES_DB}
            - KC_DB_USERNAME=${KEYCLOAK_POSTGRES_USER}
            - KC_DB_PASSWORD=${KEYCLOAK_POSTGRES_PASSWORD}
            - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USER}
            - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
            - KC_HOSTNAME=${KEYCLOAK_HOSTNAME}
            - KC_HEALTH_ENABLED=${KEYCLOAK_HEALTH_ENABLED}
            - KC_METRICS_ENABLED=${KEYCLOAK_METRICS_ENABLED}
        ports:
            - "${KEYCLOAK_HOSTNAME_PORT}:8080"
        depends_on:
            db:
                condition: service_healthy
        command: ["start-dev"] # use 'start' for optimized on production
