#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $KEYCLOAK_POSTGRES_USER WITH PASSWORD '$KEYCLOAK_POSTGRES_PASSWORD';
    CREATE DATABASE $KEYCLOAK_POSTGRES_DB;
    GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_POSTGRES_DB TO $KEYCLOAK_POSTGRES_USER;
    ALTER ROLE $KEYCLOAK_POSTGRES_USER CREATEROLE SUPERUSER;
EOSQL
echo
